spring:
  application:
  name: spring-data-mongodb

  data:
    mongodb:
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE}